### ISSUE TITLE
Use aria-current=step to provide more robust information

### ISSUE THREAD

**Issue by scottaohara** [NigelOToole/progress-tracker#10]
As the active step of this component is only visually conveyed by the existence of the `is-active` class, consider adding support for `aria-current="step"` to communicate to assistive technologies the current step.

[Explainer on `aria-current`](https://tink.uk/using-the-aria-current-attribute/)

as an example:

```html
<li aria-current="step" class="is-active"> ... </li>
```
( if not replacing the `.is-active` as the styling selector :) )

Thanks!

**Comment by NigelOToole** [comment]
That makes sense, thanks for raising this issue. The only thing Im wondering is for steps without text is this appropriate or would I need to add text for screen readers to give the step context?

**Comment by scottaohara** [comment]
depends on if the intent of the step indicator is decorative or not, and if the information would be available via other means.

for instance your basic step indicator.  
while you're using list elements here to create your progress indicator, they might as well just be `div`s because screen readers will largely choose to ignore them as there is no content presented in any of the list items.  as such, a proper use case for this sort of progress indicator would be if it was a decorative representation of what a heading might already indicate on the page.  
For example: 
```html
<!-- decorative progress indicator goes here -->
<h2>Step 2: whatever the heading text is</h2>
<!-- whatever the content is -->
```

However, if the progress indicator IS supposed to be more than just decoration and meaningful to all users, then yes, you would need to add some sort of text that could be visually hidden for the steps.

what the exact text would be would be dependent on the UI, really, but at its most generic level "Step" followed by a number or letter, or an actual text string depicting the purpose of the step (e.g. "personal information") would be provided.  THEN the lists would actually be picked up by screen readers and in that case it would then make sense to have `aria-current="step"` on the currently active step to match its visual presentation.

**Comment by NigelOToole** [comment]
Thanks for all the information, I have added this to the latest version. I have put it on the steps with text content assuming that markers without text content should have another text indicator.

**Comment by scottaohara** [comment]
Might be good to add a note about it to the readme too?  ;)
