### ISSUE TITLE
Provide a compiled CSS to make it easier for projects to use the progress tracker

### ISSUE THREAD

**Issue by jrockowitz** [NigelOToole/progress-tracker#13]
In the 2.0 branch of the progress tracker, the 'app' directory containing a built version of progress-tracker.css was removed.

The progress tracker is being used by the [Drupal Webform module](https://www.drupal.org/project/webform) and the Drupal community does not assume a site is using SASS.  I can see that the docs directory includes progress-tracker.css  without RTL support.

Would you be able to provide a compiled CSS to makes it easier for projects to use the progress tracker?

The two immediate options are to include RTL support in /docs/styles/progress-tracker.css or restore /progress-tracker/app/styles/progress-tracker.css with RTL.

I know the third option would be for me to build and include a copy of the progress-tracker.css in the Webform module. I feel this approach takes away from making sure you get the credit you deserve for solving a common problem by creating and maintaining this project.

**Comment by NigelOToole** [comment]
Thanks for the feedback, I have added RTL support in as default and the compiled file is /docs/styles/progress-tracker.css. I hope this solves your issue.

**Comment by jrockowitz** [comment]
That solves my issue. Thanks.
