### ISSUE TITLE
Consider including a compiled version of the progress tracker's css

### ISSUE THREAD

**Issue by jrockowitz** [NigelOToole/progress-tracker#27]
To allow users to load the progress tracker via a CDN would you consider adding a compiled CSS to the repos.

Currently, the only work-around is to use CSS included in the /docs/styles.

@see https://cdn.jsdelivr.net/gh/NigelOToole/progress-tracker@v2.0.6/docs/styles/progress-tracker.css

**Comment by loopy3025** [comment]
This is still an issue. A compiled version of the css at docs/styles/progress-tracker.css would be helpful. Most of the time, one is not required to delve into every library and compile css. It's extremely inconvenient.

**Comment by NigelOToole** [comment]
Compiled CSS is not included in src/styles/progress-tracker.css. Thanks for the feedback guys.

**Comment by jrockowitz** [comment]
Thanks

**Comment by cynicalgenxer** [comment]
Thank you both @NigelOToole and @jrockowitz!
@jrockowitz is there any reason why the Webform module couldn't use the minified version.  I see it's even available at the predictable location: https://cdn.jsdelivr.net/gh/NigelOToole/progress-tracker@v2.0.7/src/styles/progress-tracker.min.css

Cheers
