### ISSUE TITLE
Invalid CSS error in _progress-tracker-variables.scss

### ISSUE THREAD

**Issue by victor73** [NigelOToole/progress-tracker#28]
Getting an error when using node-sass with progress-tracker. Some details:

$ node --version
`v14.18.3`

$ node-sass --version
```
node-sass	7.0.1	(Wrapper)	[JavaScript]
libsass  	3.5.5	(Sass Compiler)	[C/C++]
```

Using a minimal test.scss file containing just one line:

`@import "node_modules/progress-tracker/src/styles/progress-tracker.scss";`

Error:
$node-sass test.scss 
```
{
  "status": 1,
  "file": "/tmp/test/node_modules/progress-tracker/src/styles/progress-tracker/_progress-tracker-variables.scss",
  "line": 19,
  "column": 30,
  "message": "Invalid CSS after \"...hird: ceil(math\": expected expression (e.g. 1px, bold), was \".div($marker-size, \"",
  "formatted": "Error: Invalid CSS after \"...hird: ceil(math\": expected expression (e.g. 1px, bold), was \".div($marker-size, \"\n        on line 19 of node_modules/progress-tracker/src/styles/progress-tracker/_progress-tracker-variables.scss\n        from line 1 of node_modules/progress-tracker/src/styles/progress-tracker.scss\n        from line 1 of test.scss\n>> $marker-size-third: ceil(math.div($marker-size, 3));\n\n   -----------------------------^\n"
}
```

**Comment by NigelOToole** [comment]
I suspect this is a problem with using node-sass as it has been deprecated. It is recommended to use sass instead now. Can you let me know if that resolves your issue?

**Comment by victor73** [comment]
Looks like you're right. Switched to sass from node-sass, and the compilation problem went away. Thank you!

**Comment by NigelOToole** [comment]
Great, glad its sorted for you.
