### ISSUE TITLE
add Right to Left plz

### ISSUE THREAD

**Issue by ziaenezhad** [NigelOToole/progress-tracker#3]
seems rtl does not work, could you please support that?
thanks

**Comment by NigelOToole** [comment]
Hi @sajjad-shirazy 

I do not have much experience with rtl development, do you have any resources or examples of how this might work?

**Comment by ziaenezhad** [comment]
Hi
please run it into the console on demo page:
`$('body').setAttribute('dir','rtl');`
you will see what i mean. thanks very much
