### ISSUE TITLE
RTL still not supported

### ISSUE THREAD

**Issue by hasnainsakir2** [NigelOToole/progress-tracker#8]
RTL is still not supported in the plugin .Can u please check it .The separate css file for RTL was commented. i uncommented it . Still not working

**Comment by NigelOToole** [comment]
Did you add [dir="rtl"] to the document html or body? If so and it still doesnt work can you upload an example so I can have a look?

**Comment by hasnainsakir2** [comment]
Sure  
![Screenshot1](https://user-images.githubusercontent.com/51268197/61047655-99914a80-a3fd-11e9-9b44-a0f241dfee10.png)
![Screenshot2](https://user-images.githubusercontent.com/51268197/61047679-a7df6680-a3fd-11e9-89a4-347adb320813.png)


the screenshot on top shows without adding dir=rtl and screenshot down shows with dir = rtl

**Comment by hasnainsakir2** [comment]
Code used by me.

///////////////////////////////////////////////////////////////////////////////////////////////////
<ul  dir="rtl" *ngIf = "mobileview == false" class="progress-tracker progress-tracker--text progress-tracker--center  progress-tracker--theme-red">
    <span></span>
  <li class="progress-step is-complete" *ngFor = "let status of trackbardata" [ngClass]="{'track-invisible': status.orderStatus.isVisibletoBuyer != true}">  
    <div class="progress-marker"></div>
     <div class="progress-text">
     <h3 *ngIf = "current_language == 'ar'" class="progress-title" class="trackbarstatus">{{status.orderStatus.ar_name}}</h3>
     <h3 *ngIf = "current_language == 'en'" class="progress-title" class="trackbarstatus">{{status.orderStatus.def_name}}</h3>
      <h3 class="trackbardate">{{status.created_date.split('T')[0] | date: 'EEE, dd MMM yyyy' }} , {{status.created_date.split('T')[1].split('.')[0]}}</h3>
   </div>
  </li>
</ul>
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by hasnainsakir2** [comment]
The code used by me


``///////////////////////////////////////////////////////////////////////////////////////////////////
<ul  dir="rtl" *ngIf = "mobileview == false" class="progress-tracker progress-tracker--text progress-tracker--center  progress-tracker--theme-red">
    <span></span>
  <li class="progress-step is-complete" *ngFor = "let status of trackbardata" [ngClass]="{'track-invisible': status.orderStatus.isVisibletoBuyer != true}">  
    <div class="progress-marker"></div>
     <div class="progress-text">
     <h3 *ngIf = "current_language == 'ar'" class="progress-title" class="trackbarstatus">{{status.orderStatus.ar_name}}</h3>
     <h3 *ngIf = "current_language == 'en'" class="progress-title" class="trackbarstatus">{{status.orderStatus.def_name}}</h3>
      <h3 class="trackbardate">{{status.created_date.split('T')[0] | date: 'EEE, dd MMM yyyy' }} , {{status.created_date.split('T')[1].split('.')[0]}}</h3>
   </div>
  </li>
</ul>
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by hasnainsakir2** [comment]
<ul  dir="rtl" *ngIf = "mobileview == false" class="progress-tracker progress-tracker--text progress-tracker--center  progress-tracker--theme-red">
    <span></span>
  <li class="progress-step is-complete" *ngFor = "let status of trackbardata" [ngClass]="{'track-invisible': status.orderStatus.isVisibletoBuyer != true}">  
    <div class="progress-marker"></div>
     <div class="progress-text">
     <h3 *ngIf = "current_language == 'ar'" class="progress-title" class="trackbarstatus">{{status.orderStatus.ar_name}}</h3>
     <h3 *ngIf = "current_language == 'en'" class="progress-title" class="trackbarstatus">{{status.orderStatus.def_name}}</h3>
      <h3 class="trackbardate">{{status.created_date.split('T')[0] | date: 'EEE, dd MMM yyyy' }} , {{status.created_date.split('T')[1].split('.')[0]}}</h3>
   </div>
  </li>
</ul>``

**Comment by hasnainsakir2** [comment]
> ///////////////////////////////////////////////////////////////////////////////////////////////////
<ul  dir="rtl" *ngIf = "mobileview == false" class="progress-tracker progress-tracker--text progress-tracker--center  progress-tracker--theme-red">
    <span></span>
  <li class="progress-step is-complete" *ngFor = "let status of trackbardata" [ngClass]="{'track-invisible': status.orderStatus.isVisibletoBuyer != true}">  
    <div class="progress-marker"></div>
     <div class="progress-text">
     <h3 *ngIf = "current_language == 'ar'" class="progress-title" class="trackbarstatus">{{status.orderStatus.ar_name}}</h3>
     <h3 *ngIf = "current_language == 'en'" class="progress-title" class="trackbarstatus">{{status.orderStatus.def_name}}</h3>
      <h3 class="trackbardate">{{status.created_date.split('T')[0] | date: 'EEE, dd MMM yyyy' }} , {{status.created_date.split('T')[1].split('.')[0]}}</h3>
   </div>
  </li>
</ul>
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by hasnainsakir2** [comment]
""""""<ul  dir="rtl" *ngIf = "mobileview == false" class="progress-tracker progress-tracker--text progress-tracker--center  progress-tracker--theme-red">
    <span></span>

**Comment by NigelOToole** [comment]
On the demo site the progress-tracker--center works fine with rtl. Looking at your screenshot it seems the demo without rtl has a line missing between pending and return. Perhaps it was some updates you made that is causing both issues. Please try the demo site again and see where the differences are.

**Comment by NigelOToole** [comment]
Sorry those code samples dont seem to have come through, can you host it
somewhere so I can look?
